// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeSszViAJ6AN2pXUKKdogf1Q3RPz5NIMU',
    appId: '1:677279088145:web:7b7d665eb42964eeae7bb0',
    messagingSenderId: '677279088145',
    projectId: 'chatapptute-151e5',
    authDomain: 'chatapptute-151e5.firebaseapp.com',
    storageBucket: 'chatapptute-151e5.appspot.com',
    measurementId: 'G-X81RELLQ7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAy85_XJkmKAgmI5TdD2mQxuyuIjP1CyM',
    appId: '1:677279088145:android:920a46856223db31ae7bb0',
    messagingSenderId: '677279088145',
    projectId: 'chatapptute-151e5',
    storageBucket: 'chatapptute-151e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAupg1DmiO-tAQFhDwgvwQYqKV1FXkKyqo',
    appId: '1:677279088145:ios:944706aed65c774cae7bb0',
    messagingSenderId: '677279088145',
    projectId: 'chatapptute-151e5',
    storageBucket: 'chatapptute-151e5.appspot.com',
    iosBundleId: 'com.example.flutterExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAupg1DmiO-tAQFhDwgvwQYqKV1FXkKyqo',
    appId: '1:677279088145:ios:944706aed65c774cae7bb0',
    messagingSenderId: '677279088145',
    projectId: 'chatapptute-151e5',
    storageBucket: 'chatapptute-151e5.appspot.com',
    iosBundleId: 'com.example.flutterExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeSszViAJ6AN2pXUKKdogf1Q3RPz5NIMU',
    appId: '1:677279088145:web:4fe0336638b9bf39ae7bb0',
    messagingSenderId: '677279088145',
    projectId: 'chatapptute-151e5',
    authDomain: 'chatapptute-151e5.firebaseapp.com',
    storageBucket: 'chatapptute-151e5.appspot.com',
    measurementId: 'G-LN8V4DM5DW',
  );
}
